### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by CloudNiner** [ashwin-sureshkumar/angular-cache-service-blog#1]
Hi, cool cache service example! In order for me to use the code in a derivative work, this repo would need to have a license associated with it. Hope you can add one that fits your needs.

See https://choosealicense.com/ for more info if you're unfamiliar with some of the more commonly used options.

**Comment by ashwin-sureshkumar** [comment]
@CloudNiner - Thanks ! I have added the license.

**Comment by CloudNiner** [comment]
Nice! Thanks for the quick response.
